In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("./test.csv")

df.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011

In [4]:
s = pd.Series([1, 2, 3], index=["I__", "II_", "III"])

s

I__    1
II_    2
III    3
dtype: int64

In [7]:
df.describe()

,Id,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
count,41.000000,41.000000,41.000000,41.000000,0.0,41.000000,41.000000,41.0
mean,21.000000,186392.179756,47562.430732,59340.690488,NaN,293295.300976,293295.300976,2011.0
std,11.979149,63935.790994,52455.606154,77190.088172,NaN,63993.574136,63993.574136,0.0
min,1.000000,77916.000000,0.000000,0.000000,NaN,251685.160000,251685.160000,2011.0
25%,11.000000,140546.860000,0.000000,16115.860000,NaN,260297.660000,260297.660000,2011.0
50%,21.000000,174872.640000,50227.610000,25972.640000,NaN,274190.270000,274190.270000,2011.0
75%,31.000000,254027.630000,77896.140000,67083.830000,NaN,299494.170000,299494.170000,2011.0
max,41.000000,294580.020000,245131.880000,400184.250000,NaN,567595.430000,567595.430000,2011.0

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Id                41 non-null     int64
 1   EmployeeName      41 non-null     object
 2   JobTitle          41 non-null     object
 3   BasePay           41 non-null     float64
 4   OvertimePay       41 non-null     float64
 5   OtherPay          41 non-null     float64
 6   Benefits          0 non-null      float64
 7   TotalPay          41 non-null     float64
 8   TotalPayBenefits  41 non-null     float64
 9   Year              41 non-null     int64
dtypes: float64(6), int64(2), object(2)
memory usage: 3.3+ KB